# üî¨ Grouping and Aggregating Data with Pandas

üëâ A very common task in working with data is to *summarize* your data by one or more criteria. As an example, you may want to find out the average salary of employees **by department**. Pandas allows you to use a [*split-apply-combine*](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) pattern to perform those types of tasks.

‚ñ∂Ô∏è First, run the code cell below to import `unittest`, a module used for **üß≠ Check Your Work** sections.

In [ ]:
import unittest
tc = unittest.TestCase()

#### üëá Tasks

- ‚úîÔ∏è Import the following Python packages.
    1. `pandas`: Use alias `pd`.
    2. `numpy`: Use alias `np`.

In [ ]:
# YOUR CODE BEGINS


# YOUR CODE ENDS

#### üß≠ Check your work

- Once you're done, run the code cell below to test correctness.
- ‚úîÔ∏è If the code cell runs without an error, you're good to move on.
- ‚ùå If the code cell throws an error, go back and fix incorrect parts.

In [ ]:
import sys
tc.assertTrue('pd' in globals(), 'Check whether you have correctly import Pandas with an alias.')
tc.assertTrue('np' in globals(), 'Check whether you have correctly import NumPy with an alias.')

---

### üìå Create employees data

‚ñ∂Ô∏è Run the code cell below to create a new `DataFrame` named `df`.

In [ ]:
df = pd.DataFrame({
    'name': ['Mary', 'Roy', 'John', 'Joe', 'Paul', 'Erin'],
    'dept': ['Finance', 'Purchase', 'Finance', 'Purchase', 'Finance', 'Purchase'],
    'salary': [240000, 160000, 250000, 170000, 260000, 180000]}
)

df

---

### üìå Creating a `DataFrameGroupBy` object

‚ñ∂Ô∏è Run `df.groupby('dept')` below.

In [ ]:
# YOUR CODE BEGINS

# YOUR CODE ENDS

#### Notes

- Internally, Pandas will create one group per department when you run `.groupby('dept')`.
- However, you will be able to see the groups until we apply aggregation function(s) to each group.
- The strange-looking output (in the form of `<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000012345678910>`) tells us that the result is a `DataFrameGroupBy` object.
- The diagram below describes what Pandas is doing behind the scene.

![groupby object](https://github.com/bdi475/images/blob/main/pandas/df-groupby-object-01.png?raw=true)

---

### üìå Aggregating a `DataFrameGroupBy` object

‚ñ∂Ô∏è Run `df.groupby('dept').agg({'salary': 'mean'})` below.

In [ ]:
# YOUR CODE BEGINS

# YOUR CODE ENDS

üëâ Your resulting `DataFrame` now displays average salary by `dept`.

#### Columns used as "pivots"

```python
df_salary_by_dept = df.groupby('dept').agg({'salary': 'mean'})

display(df_salary_by_dept)
print(df_salary_by_dept.columns)
```

‚ñ∂Ô∏è Copy the provided code above to the code cell below and run it.

In [ ]:
# YOUR CODE BEGINS




# YOUR CODE ENDS

üëâ There is only one column shown when you print out `df_salary_by_dept.columns`! üôÄ

This is because the column(s) you use to create groups are used as **index** by default.

![groupby agg result](https://github.com/bdi475/images/blob/main/pandas/df-groupby-agg-as-index-true-01.png?raw=true)

---

### üìå Aggregating a `DataFrameGroupBy` object with optional `index=False`

```python
df_salary_by_dept2 = df.groupby('dept', as_index=False).agg({'salary': 'mean'})

display(df_salary_by_dept2)
print(df_salary_by_dept2.columns)
```

‚ñ∂Ô∏è Copy the provided code to the code cell below and run it.

In [ ]:
# YOUR CODE BEGINS




# YOUR CODE ENDS

üëâ Now, printing out the columns show both `dept` and `salary`. Supplying `as_index=False` to `groupby()` keeps the columns you use as the "pivot" as regular columns.

![groupby agg result](https://github.com/bdi475/images/blob/main/pandas/df-groupby-agg-as-index-false-01.png?raw=true)

---

### üìå Creating multiple aggregation measures

```python
df_salary_by_dept3 = df.groupby('dept', as_index=False).agg({'salary': ['min', 'max', 'mean', 'sum', 'count', 'std']})

display(df_salary_by_dept3)
print(df_salary_by_dept3.columns)
```

‚ñ∂Ô∏è Copy the provided code to the code cell below and run it.

In [ ]:
# YOUR CODE BEGINS




# YOUR CODE ENDS

---

### üìå Flattening multi-level index columns

When you apply two or more aggregation functions to a column, your DataFrame creates a hierarchically structured columns. It is often easier to work with a DataFrame if you have a flat-level columns. You can manually assign the column names after `.agg()` in these cases to *flatten* the columns.

```python
df_salary_by_dept4 = df.groupby('dept', as_index=False).agg({'salary': ['min', 'max', 'mean', 'sum', 'count', 'std']})

display(df_salary_by_dept4)
print('Columns before (multi-level, not flat):')
print(df_salary_by_dept4.columns)

# manually assign column names
df_salary_by_dept4.columns = ['dept', 'min_salary', 'max_salary', 'mean_salary', 'total_salary', 'num_employees', 'std_dev']

display(df_salary_by_dept4)
print('Columns after (flat-level):')
print(df_salary_by_dept4.columns)
```

‚ñ∂Ô∏è Copy the provided code to the code cell below and run it.

In [ ]:
df_salary_by_dept4 = df.groupby('dept', as_index=False).agg({'salary': ['min', 'max', 'mean', 'sum', 'count', 'std']})

display(df_salary_by_dept4)
print('Columns before (multi-level, not flat):')
print(df_salary_by_dept4.columns)

# manually assign column names
df_salary_by_dept4.columns = ['dept', 'min_salary', 'max_salary', 'mean_salary', 'total_salary', 'num_employees', 'std_dev']

display(df_salary_by_dept4)
print('Columns after (flat-level):')
print(df_salary_by_dept4.columns)

---

## üìû Exercises Using Bank Marketing Calls Data

For the next part of this lecture, you'll work with a dataset related with direct marketing campaigns (phone calls) of a banking institution. 

**Data Source**: [Moro et al., 2014] S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems, Elsevier, 62:22-31, June 2014

| Column Name     | Type        | Description                                                                                                                                                     |
|-----------------|-------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `age`           | Numeric     | Age                                                                                                                                                             |
| `job`           | Categorical | admin.', 'blue-collar',   'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed',   'services', 'student', 'technician', 'unemployed', 'unknown' |
| `marital`       | Categorical | single', 'married', 'divorced', 'unknown'                                                                                                                       |
| `education`     | Categorical | basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate',   'professional.course', 'university.degree', 'unknown'                                         |
| `contact_type`  | Categorical | cellular', 'telephone'                                                                                                                                          |
| `num_contacts`  | Numeric     | Number of contacts performed during this campaign for this client                                                                                               |
| `prev_outcome`  | Categorical | Outcome of the previous marketing campaign - 'failure', 'nonexistent',   'success'                                                                              |
| `place_deposit` | Numeric     | Did the client subscribe to a term deposit? This column indicates whether the campaign was successful (1) or not (0) for each client.                                        |

---


Your goal is to analyze the dataset to discover relationships between personal factors and marketing campaign result of each individual.

**`place_deposit`** column indicates whether a marketing campaign was successful.
z
- ‚úÖ If `1`, the individual has placed a deposit within the bank. This is considered a **successful campaign**.
- üö´ If `0`, the individual has not placed a deposit within the bank. This is considered an **unsuccessful campaign**.

---

### üìå Load data

‚ñ∂Ô∏è Run the code cell below to create a new `DataFrame` named `df_m`.

In [ ]:
df_m = pd.read_csv('bank-direct-marketing.csv')
df_m_backup = df_m.copy()
df_m

---

### üéØ Challenge 1: Marketing success rate by marital status

#### üëá Tasks

- ‚úîÔ∏è Using `df_m`, create an aggregated table named `df_by_marital` that lists the success rate (average of the `place_deposit` column) by marital status.
- ‚úîÔ∏è Use the `as_index=False` option.
- ‚úîÔ∏è The aggregated DataFrame should have two columns - "marital" and "success_rate".
- ‚úîÔ∏è `df_by_marital` should only have the following two columns in the same order.
    - `marital`: Marital status (e.g., single, divorced, married, unknown)
    - `success_rate`: Average success rate (between 0-1)
- ‚úîÔ∏è Both columns should not be used as an index column.
    - Printing `df_by_marital.columns.to_list()` should print out `['marital', 'success_rate']`.
- ‚úîÔ∏è Sort `df_by_marital` by `success_rate` in descending order *in-place*.

#### üîë Expected Output

|    | marital   |   success_rate |
|---:|:----------|---------------:|
|  3 | unknown   |       0.15     |
|  2 | single    |       0.140041 |
|  0 | divorced  |       0.103209 |
|  1 | married   |       0.101573 |

In [ ]:
# YOUR CODE BEGINS



# YOUR CODE ENDS

df_by_marital

#### üß≠ Check Your Work

- Once you're done, run the code cell below to test correctness.
- ‚úîÔ∏è If the code cell runs without an error, you're good to move on.
- ‚ùå If the code cell throws an error, go back and fix incorrect parts.

In [ ]:
df_check = df_m_backup.groupby('marital', as_index=bool(0)).agg({'place_deposit': np.mean}) \
    .rename(columns={'_'.join(['place', 'deposit']): 'success_rate'}) \
    .sort_values('success_rate').iloc[::-1]
df_check = df_check[['success_rate', 'marital'][::-1]].copy()

# Check result
pd.testing.assert_frame_equal(df_by_marital.reset_index(drop=True),
                              df_check.reset_index(drop=True))

---

### üéØ Challenge 2: Marketing success rate by job

#### üëá Tasks

- ‚úîÔ∏è Using `df_m`, create an aggregated table named `df_by_job` to that lists the average success rate in direct marketing campaigns by job.
- ‚úîÔ∏è Use the `as_index=False` option.
- ‚úîÔ∏è `df_by_job` should only have the following two columns in the same order.
    - `job`: Job (e.g., student, technician, housemaid, etc)
    - `success_rate`: Average success rate (between 0-1)
- ‚úîÔ∏è Both columns should not be used as an index column.
    - Printing `df_by_job.columns.to_list()` should print out `['job', 'success_rate']`.
- ‚úîÔ∏è Sort `df_by_job` by `success_rate` in descending order.

#### üîë Expected Output

|    | job           |   success_rate |
|---:|:--------------|---------------:|
|  8 | student       |      0.314286  |
|  5 | retired       |      0.252326  |
| 10 | unemployed    |      0.142012  |
|  0 | admin.        |      0.129726  |
|  4 | management    |      0.112175  |
| 11 | unknown       |      0.112121  |
|  9 | technician    |      0.10826   |
|  6 | self-employed |      0.104856  |
|  3 | housemaid     |      0.1       |
|  2 | entrepreneur  |      0.0851648 |
|  7 | services      |      0.0813807 |
|  1 | blue-collar   |      0.0689432 |

In [ ]:
# YOUR CODE BEGINS



# YOUR CODE ENDS

df_by_job

#### üß≠ Check Your Work

- Once you're done, run the code cell below to test correctness.
- ‚úîÔ∏è If the code cell runs without an error, you're good to move on.
- ‚ùå If the code cell throws an error, go back and fix incorrect parts.

In [ ]:
# DO NOT CHANGE THE CODE BELOW
df_check = df_m_backup.groupby('job').agg({'place_deposit': np.mean}).reset_index() \
    .rename(columns={'_'.join(['place', 'deposit']): 'success_rate'}) \
    .sort_values('success_rate').iloc[::-1]
df_check = df_check[['success_rate', 'job'][::-1]].copy()

pd.testing.assert_frame_equal(df_by_job.reset_index(drop=True),
                              df_check.reset_index(drop=True))

---

### üéØ Challenge 3: Marketing success rate by contact type with count

#### üëá Tasks

- ‚úîÔ∏è Using `df_m`, create an aggregated table named `df_by_contact_type` that lists the number of campaigns and the average success rate by contact type.
- ‚úîÔ∏è Use the `as_index=False` option.
- ‚úîÔ∏è `df_by_contact_type` should only have the following three columns in the same order.
    - `contact_type`: Contact method (e.g., cellular, telephone)
    - `count`: Number of potential customers that were contacted using the corresponding contact type
    - `success_rate`: Average success rate (between 0-1)
- ‚úîÔ∏è All three columns should not be used as an index column.
    - Printing `df_by_contact_type.columns.to_list()` should print out `['contact_type', 'count', 'success_rate']`.
- ‚úîÔ∏è Sort `df_by_contact_type` by `success_rate` in descending order.

#### üîë Expected Output

|    | contact_type   |   count |   success_rate |
|---:|:---------------|--------:|---------------:|
|  0 | cellular       |   26144 |      0.147376  |
|  1 | telephone      |   15044 |      0.0523132 |

In [ ]:
# YOUR CODE BEGINS








# YOUR CODE ENDS
df_by_contact_type

#### üß≠ Check Your Work

- Once you're done, run the code cell below to test correctness.
- ‚úîÔ∏è If the code cell runs without an error, you're good to move on.
- ‚ùå If the code cell throws an error, go back and fix incorrect parts.

In [ ]:
# DO NOT CHANGE THE CODE BELOW
df_check = df_m_backup.groupby('_'.join(['contact', 'type'])).agg({'place_deposit': ['count', np.mean]}).reset_index()
df_check.columns = ['SUCCESS_RATE'.lower(), 'COUNT'.lower(), 'CONTACT_TYPE'.lower()][::-1]
df_check = df_check \
    .sort_values('success_rate').iloc[::-1]

pd.testing.assert_frame_equal(df_by_contact_type.reset_index(drop=True),
                              df_check.reset_index(drop=True))

---

### üìå Grouping by multiple columns

You can run a `groupby()` with two or more columns by supplying a `list` of columns to the `groupby()` function.

```python
# example
df.groupby(['column1', 'column2'], as_index=False).agg({ 'column3': ... })
```

---

### üéØ Challenge 4: Marketing success rate by marital status and contact type

#### üëá Tasks

- ‚úîÔ∏è Using `df_m`, create an aggregated table named `df_by_type_and_marital` that lists the average success rate in direct marketing campaigns by marital status and contact type.
- ‚úîÔ∏è Use the `as_index=False` option.
- ‚úîÔ∏è `df_by_type_and_marital` should only have the following three columns in the same order.
    - `marital`: Marital status (e.g., single, divorced, married, unknown)
    - `contact_type`: Contact method (e.g., cellular, telephone)
    - `success_rate`: Average success rate (between 0-1)
- ‚úîÔ∏è All three columns should not be used as an index column.
    - Printing `df_by_type_and_marital.columns.to_list()` should print out `['marital', 'contact_type', 'success_rate']`.
- ‚úîÔ∏è Sort `df_by_type_and_marital` by `success_rate` in descending order.

#### üîë Expected Output

|    | marital   | contact_type   |   success_rate |
|---:|:----------|:---------------|---------------:|
|  6 | unknown   | cellular       |      0.207547  |
|  4 | single    | cellular       |      0.173875  |
|  0 | divorced  | cellular       |      0.13652   |
|  2 | married   | cellular       |      0.135341  |
|  5 | single    | telephone      |      0.0648844 |
|  3 | married   | telephone      |      0.0487554 |
|  1 | divorced  | telephone      |      0.0463615 |
|  7 | unknown   | telephone      |      0.037037  |

In [ ]:
# YOUR CODE BEGINS





# YOUR CODE ENDS

df_by_type_and_marital

#### üß≠ Check Your Work

- Once you're done, run the code cell below to test correctness.
- ‚úîÔ∏è If the code cell runs without an error, you're good to move on.
- ‚ùå If the code cell throws an error, go back and fix incorrect parts.

In [ ]:
# DO NOT CHANGE THE CODE BELOW
df_check = df_m_backup.groupby(['MARITAL'.lower(), '_'.join(['contact', 'type'])]) \
    .agg({'place_deposit': np.mean}).reset_index()
df_check.rename(columns={'place_deposit': '_'.join(['SUCCESS', 'RATE']).lower()}, inplace=bool(1))
df_check = df_check \
    .sort_values('success_rate').iloc[::-1]

pd.testing.assert_frame_equal(df_by_type_and_marital.reset_index(drop=True),
                              df_check.reset_index(drop=True))